language: java

before_install: ant download-ivy
install: ant all

node_js:
  - "0.12"

branches:
  only:
    - master

script:
  - npm run-script lint

notifications:
  email: false

jdk:
  - oraclejdk8
